<!-- section -->
<div class="section content-wrapper">
    <div class="container banner">
        <!-- home slick -->
        <div id="home-slick">
            <!-- banner -->
            <div class="banner banner-1">
                <img height="450px" src="<?php echo STATIC_URL; ?>/uploads/images/banner/banner-nhathepsaigon-1.jpg" alt="<?php echo $this->arrConfig['web_name']; ?>">
            </div>
            <!-- /banner -->
            <!-- banner -->
            <div class="banner banner-1">
                <img height="450px" src="<?php echo STATIC_URL; ?>/uploads/images/banner/banner-nhathepsaigon-2.JPG" alt="<?php echo $this->arrConfig['web_name']; ?>">
            </div>
            <!-- /banner -->
            <!-- banner -->
            <div class="banner banner-1">
                <img height="450px" src="<?php echo STATIC_URL; ?>/uploads/images/banner/banner-nhathepsaigon-3.JPG" alt="<?php echo $this->arrConfig['web_name']; ?>">
            </div>
            <!-- /banner -->
            <!-- banner -->
            <div class="banner banner-1">
                <img height="450px" src="<?php echo STATIC_URL; ?>/uploads/images/banner/banner-nhathepsaigon-4.JPG" alt="<?php echo $this->arrConfig['web_name']; ?>">
            </div>
            <!-- /banner -->
            <!-- banner -->
            <div class="banner banner-1">
                <img height="450px" src="<?php echo STATIC_URL; ?>/uploads/images/banner/banner-nhathepsaigon-5.jpg" alt="<?php echo $this->arrConfig['web_name']; ?>">
            </div>
            <!-- /banner -->
            <!-- banner -->
            <div class="banner banner-1">
                <img height="450px" src="<?php echo STATIC_URL; ?>/uploads/images/banner/banner-nhathepsaigon-6.JPG" alt="<?php echo $this->arrConfig['web_name']; ?>">
            </div>
            <!-- /banner -->
            <!-- banner -->
            <div class="banner banner-1">
                <img height="450px" src="<?php echo STATIC_URL; ?>/uploads/images/banner/banner-nhathepsaigon-7.jpg" alt="<?php echo $this->arrConfig['web_name']; ?>">
            </div>
            <!-- /banner -->
            <!-- banner -->
            <div class="banner banner-1">
                <img height="450px" src="<?php echo STATIC_URL; ?>/uploads/images/banner/banner-nhathepsaigon-8.jpg" alt="<?php echo $this->arrConfig['web_name']; ?>">
            </div>
            <!-- /banner -->
        </div>
        <!-- /home slick -->
    </div>
</div>
<!-- /section -->