<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name='viewport' content='width=device-width, initial-scale=1, user-scalable=yes' />
<link rel="shortcut icon" type="image/png" href="<?php echo STATIC_URL; ?>/fe/images/favicon.png" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-title" content="<?php echo $this->arrConfig['web_link']; ?>" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />

<meta name="dc.created" content="2019-04-10" />
<meta name="dc.publisher" content="<?php echo $this->arrConfig['web_name']; ?>" />
<meta name="dc.rights.copyright" content="<?php echo $this->arrConfig['web_name']; ?>" />
<meta name="dc.creator.name" content="<?php echo $this->arrConfig['web_name']; ?>" />
<meta name="dc.creator.email" content="<?php echo $this->arrConfig['email']; ?>" />
<meta name="dc.identifier" content="<?php echo $this->arrConfig['web_link']; ?>" />
<meta name="copyright" content="<?php echo $this->arrConfig['web_name']; ?>" />
<meta name="author" content="<?php echo $this->arrConfig['web_name']; ?>" />
<meta name="dc.language" content="vi-VN" />

<!--Geo-Tags-->
<meta name="geo.region" content="VN-SG" />
<meta name="geo.placename" content="Ho Chi Minh, Viet Nam" />
<meta name="geo.position" content="10.826585;106.706604" />
<meta name="ICBM" content="10.826585, 106.706604" />
<!-- Schema.org markup for Google+ -->
<meta itemprop="name" content="<?php echo $this->strMetaTitle; ?>">
<meta itemprop="description" content="<?php echo $this->strMetaDesc; ?>">
<meta itemprop="image" content="<?php echo $this->strMetaImage; ?>">
<!-- Twitter Card -->
<meta name="twitter:card" value="summary_large_image">
<meta name="twitter:site" content="@<?php echo $this->arrConfig['web_name']; ?>">
<meta name="twitter:creator" content="@<?php echo $this->arrConfig['web_name']; ?>">
<meta name="twitter:title" content="<?php echo $this->strMetaTitle; ?>">
<meta name="twitter:description" content="<?php echo $this->strMetaDesc; ?>">
<meta name="twitter:image" content="<?php echo $this->strMetaImage; ?>"/>
<meta name="twitter:url" content="<?php echo $this->strMetaUrl; ?>">
<!-- End Twitter Card -->
<!-- Open Graph data -->
<meta property="og:site_name" content="<?php echo $this->arrConfig['web_name']; ?>" />
<meta property="og:type" content="article" />
<meta property="og:title" itemprop="headline" content="<?php echo $this->strMetaTitle; ?>" />
<meta property="og:url" itemprop="url" content="<?php echo $this->strMetaUrl; ?>" />
<meta property="og:image" itemprop="thumbnailUrl" content="<?php echo $this->strMetaImage; ?>" />
<meta property="og:description" itemprop="description" content="<?php echo $this->strMetaDesc; ?>" />
<meta property="fb:pages" content="1049537515243676" />
<meta property="fb:app_id" content="1932831253489361"/>
<meta property="fb:admins" content="1846055054"/>

<meta name="author" content="<?php echo $this->arrConfig['web_name']; ?>" />
<meta name="copyright" content="Copyright (c) 2019 by <?php echo $this->arrConfig['web_name']; ?>" />
<meta http-equiv="content-language" content="vi"/>
<meta name="revisit-after" content="days">
<meta name="robots" content="index,follow" />
<meta http-equiv="REFRESH" content="1800" />
<?php
echo $this->headTitle();
echo $this->headMeta();
?>
<link rel="canonical" href="<?php echo $this->strMetaUrl; ?>" />
<link rel="author" href="https://plus.google.com/113970991101972364481"/>
<link rel="publisher" href="https://plus.google.com/113970991101972364481"/>
<!-- iPad icons -->
<link rel="apple-touch-icon-precomposed" href="<?php echo STATIC_URL; ?>/fe/images/logos/72x72.png" sizes="72x72" />
<link rel="apple-touch-icon-precomposed" href="<?php echo STATIC_URL; ?>/fe/images/logos/114x114.png" sizes="144x144" />
<!-- iPhone and iPod touch icons -->
<link rel="apple-touch-icon-precomposed" href="<?php echo STATIC_URL; ?>/fe/images/logos/57x57.png" sizes="57x57" />
<link rel="apple-touch-icon-precomposed" href="<?php echo STATIC_URL; ?>/fe/images/logos/114x114.png" sizes="144x144" />
<!-- Nokia Symbian -->
<link rel="nokia-touch-icon" href="<?php echo STATIC_URL; ?>/fe/images/logos/57x57.png" />
<!-- Android icon precomposed so it takes precedence -->
<link rel="apple-touch-icon-precomposed" href="<?php echo STATIC_URL; ?>/fe/images/logos/114x114.png" sizes="1x1" />

<!-- Bootstrap 3.3.5 -->
<link href="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/css/bootstrap<?php echo EXT; ?>.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/css/bootstrap-theme<?php echo EXT; ?>.css" rel="stylesheet" type="text/css"/>
<!-- Font Awesome Icons -->
<link href="<?php echo STATIC_URL; ?>/library/font-awesome-4.6.3/css/font-awesome<?php echo EXT; ?>.css" rel="stylesheet" type="text/css" />
<!-- Pushy CSS -->
<link href="<?php echo STATIC_URL; ?>/fe/css/pushy<?php echo EXT; ?>.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo STATIC_URL; ?>/fe/css/slick<?php echo EXT; ?>.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo STATIC_URL; ?>/fe/css/slick-theme<?php echo EXT; ?>.css" rel="stylesheet" type="text/css"/>
<link href="<?php echo STATIC_URL; ?>/fe/css/main<?php echo EXT; ?>.css" rel="stylesheet" type="text/css"/>
<?php
echo $this->headLink();
?>

<script type="text/javascript">
    var SITE_URL = '<?php echo SITE_URL;?>';
    var STATIC_URL = '<?php echo STATIC_URL;?>';
    var document.domain = '<?php echo DOMAIN;?>';
</script>
<?php
if (SITE_URL == 'http://nhathepsaigon.vn') {
    ?>
    <!-- TRACKING GOOGLE -->
    <script type="text/javascript">
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-92297673-1', 'auto');
        ga('send', 'pageview');

    </script>
    <!-- END TRACKING GOOGLE -->
    <script>
        //Tracking event
        function trackingEvent($a, $b, $c) {
            _gaq.push(['_trackEvent', $a, $b, $c]);
        }
    </script>
    <!-- Google webmaster -->
    <meta name="google-site-verification" content="uCmdv3cvp-hHGTcX8jRp8MMJDYW9s1g62Db8CZ4xhNw"/>
    <!-- Google Tag Manager -->
    <script>(function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-NXZTG6S');</script>
    <!-- End Google Tag Manager -->
    <!-- Global site tag (gtag.js) - Google Ads: 864599838 -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=AW-864599838"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'AW-864599838');
    </script>
    <!-- Facebook Pixel Code -->
    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '315241992473524');
        fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
                   src="https://www.facebook.com/tr?id=315241992473524&ev=PageView&noscript=1"/></noscript>
    <!-- End Facebook Pixel Code -->
    <!--Facebook-->
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: 'v3.3',
                cookie: true,
                xfbml: true,
                version: '1932831253489361'
            });

            FB.AppEvents.logPageView();

        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {
                return;
            }
            js = d.createElement(s);
            js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <!--End facebook-->
    <script id='autoAdsMaxLead-widget-script' src='https://cdn.autoads.asia/scripts/autoads-maxlead-widget.js?business_id=AE6745E0A9BD4E8D8D4148460439B403' type='text/javascript' charset='UTF-8' async></script>
    <?php
} else {
    ?>
    <!-- TRACKING GOOGLE -->
    <script type="text/javascript">
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-67636917-1', 'auto');
        ga('send', 'pageview');

    </script>
    <!-- END TRACKING GOOGLE -->
    <script>
        //Tracking event
        function trackingEvent($a, $b, $c) {
            _gaq.push(['_trackEvent', $a, $b, $c]);
        }
    </script>
    <!-- Google webmaster -->
    <meta name="google-site-verification" content="iWbe7iMfBGLGA3Hhdui3NxUXiPaXi6rOZQMMgERC9vU" />
    <!-- Google Tag Manager -->
    <script>(function (w, d, s, l, i) {
            w[l] = w[l] || [];
            w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            });
            var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
            j.async = true;
            j.src =
                'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
            f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-GTM-M2J9HX');</script>
    <!-- End Google Tag Manager -->
    <!-- Facebook Pixel Code -->
    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '315241992473524');
        fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
                   src="https://www.facebook.com/tr?id=315241992473524&ev=PageView&noscript=1"/></noscript>
    <!-- End Facebook Pixel Code -->
    <!--Facebook-->
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: 'v3.3',
                cookie: true,
                xfbml: true,
                version: '1932831253489361'
            });

            FB.AppEvents.logPageView();

        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {
                return;
            }
            js = d.createElement(s);
            js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <!--End facebook-->
    <?php
}
?>
<script type="application/ld+json">
    {
        "@context" : "http://schema.org",
        "@type" : "WebSite",
        "name" : "<?php echo $this->arrConfig['web_name']; ?>",
        "alternateName" : "<?php echo $this->arrConfig['web_name']; ?>",
        "url" : "<?php echo $this->arrConfig['web_link']; ?>"
    }
</script>
<script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [{
            "@type": "ListItem",
            "position": 1,
            "item": {
                "@id": "<?php echo $this->arrConfig['web_link']; ?>",
                "name": "Trang chủ"
            }
        },{
            "@type": "ListItem",
            "position": 2,
            "item": {
                "@id": "http://nhathepsaigon.vn/gioi-thieu.html",
                "name": "Giới thiệu"
            }
        },{
            "@type": "ListItem",
            "position": 3,
            "item": {
                "@id": "http://nhathepsaigon.vn/bang-gia.html",
                "name": "Bảng giá"
            }
        },{
            "@type": "ListItem",
            "position": 4,
            "item": {
                "@id": "http://nhathepsaigon.vn/tin-tuc/thiet-ke-kien-truc",
                "name": "Thiết kế kiến trúc"
            }
        },{
            "@type": "ListItem",
            "position": 5,
            "item": {
                "@id": "http://nhathepsaigon.vn/tin-tuc/nha-thep",
                "name": "Nhà thép"
            }
        },{
            "@type": "ListItem",
            "position": 6,
            "item": {
                "@id": "http://nhathepsaigon.vn/tin-tuc/nha-dep",
                "name": "Nhà đẹp"
            }
        },{
            "@type": "ListItem",
            "position": 7,
            "item": {
                "@id": "http://nhathepsaigon.vn/tin-tuc/tu-van",
                "name": "Tư vấn"
            }
        },{
            "@type": "ListItem",
            "position": 8,
            "item": {
                "@id": "http://nhathepsaigon.vn/lien-he.html",
                "name": "Liên hệ"
            }
        }]
    }
</script>
<?php
if($this->controllerName=='detail' && $this->actionName=='index') {
    ?>
    <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@type": "NewsArticle",
            "mainEntityOfPage": {
                "@type": "WebPage",
                "@id": "<?php echo $this->strMetaUrl; ?>"
            },
            "headline": "<?php echo $this->strMetaTitle; ?>",
            "url": "<?php echo $this->strMetaUrl; ?>",
            "image": {
                "@type": "ImageObject",
                "url": "<?php echo $this->strMetaImage; ?>",
                "height": 800,
                "width": 800
            },
            "datePublished": "<?php echo date(DateTime::ISO8601, $this->arrArticleDetail['ptime']); ?>",
            "dateModified": "<?php echo date(DateTime::ISO8601, $this->arrArticleDetail['ptime']); ?>",
            "author": {
                "@type": "Person",
                "name": "<?php echo $this->arrConfig['web_name']; ?>"
            },
            "publisher": {
                "@type": "Organization",
                "name": "<?php echo $this->arrConfig['web_name']; ?>",
                "logo": {
                    "@type": "ImageObject",
                    "url": "<?php echo STATIC_URL; ?>/fe/images/logo.png",
                    "width": 600,
                    "height": 60
                }
            },
            "keywords": ["<?php echo $this->strMetaKeyword; ?>"],
            "description": "<?php echo $this->strMetaDesc; ?>"
        }
    </script>
    <?php
}
?>
