<div class="modal fade" id="modal-loading" role="dialog" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Thông báo</h4>
            </div>
            <div class="modal-body">
                <span style="color: #d71450;">Hệ thống đang xử lý...!</span>
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-default" type="button">Đóng</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>