<?php
$arrReturn = $this->arrReturn;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <ol class="breadcrumb">
            <li><a href="<?php echo SITE_URL;?>/backend"><i class="fa fa-th"></i> Dashboard</a></li>
            <li><a href="<?php echo SITE_URL;?>/backend/pages/index" title="Trang tĩnh">Trang tĩnh</a></li>
            <li><a href="<?php echo SITE_URL;?>/backend/pages/add" title="Tạo trang tĩnh">Tạo trang tĩnh</a></li>
        </ol>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!--<div class="callout callout-info">
        <h4>Thông báo</h4>
        <p>Cập nhật thành công</p>
    </div>-->
    <div class="row">
        <form id="add" enctype="multipart/form-data" accept-charset="utf-8" method="post" action="" role="form">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Tạo trang tĩnh</h3>
                    </div>
                    <div class="box-body">
                        <div class="form-group frm-validate">
                            <div class="row">
                                <div class="col-md-9">
                                    <!--<div class="form-group frm-validate">
                                        <label for="strPageKey">Key page</label>
                                        <input name="strPageKey" type="text" value="<?php echo isset($arrReturn['data']['strPageKey']) ? $arrReturn['data']['strPageKey'] : ''; ?>" class="form-control" id="strPageKey">
                                    </div>-->
                                    <div class="form-group frm-validate">
                                        <label for="strName">Name</label>
                                        <input name="strName" type="text" value="<?php echo isset($arrReturn['data']['strName']) ? $arrReturn['data']['strName'] : ''; ?>" class="form-control" id="strName">
                                    </div>
                                    <div class="form-group frm-validate">
                                        <label for="strMetaTitle">Meta title</label>
                                        <input name="strMetaTitle" type="text" value="<?php echo isset($arrReturn['data']['strMetaTitle']) ? $arrReturn['data']['strMetaTitle'] : ''; ?>" class="form-control" id="strMetaTitle">
                                    </div>
                                    <div class="form-group frm-validate">
                                        <label for="strMetaDesc">Meta description</label>
                                        <textarea class="form-control" style="width: 100%;" rows="4" cols="118" name="strMetaDesc" id="strMetaDesc"><?php echo isset($arrReturn['data']['strMetaDesc']) ? $arrReturn['data']['strMetaDesc'] : ''; ?></textarea>
                                    </div>
                                    <div class="form-group frm-validate">
                                        <label for="strMetaKeyword">Meta keyword</label>
                                        <input name="strMetaKeyword" type="text" value="<?php echo isset($arrReturn['data']['strMetaKeyword']) ? $arrReturn['data']['strMetaKeyword'] : ''; ?>" class="form-control" id="strMetaKeyword">
                                    </div>
                                    <div class="form-group frm-validate">
                                        <label for="ckeditor">Nội dung trang tĩnh</label>
                                        <textarea name="ckeditor" id="ckeditor">
                                            <?php
                                            echo isset($arrReturn['data']['ckeditor']) && $arrReturn['data']['ckeditor'] != '' ? $arrReturn['data']['ckeditor'] : 'Nội dung';
                                            ?>
                                        </textarea>
                                    </div>
                                    <div class="form-group frm-validate">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <label for="strDate">Thời gian đăng bài</label>
                                                <input name="strDate" type="text" value="<?php echo isset($arrReturn['data']['strDate']) && $arrReturn['data']['strDate'] != '' ? $arrReturn['data']['strDate']:'';?>" class="form-control" id="strDate">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group frm-validate">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <label for="strMetaKeyword">Status</label>
                                                <select class="form-control" name="intStatus">
                                                    <option value="1"<?php echo isset($arrReturn['data']['intStatus']) && $arrReturn['data']['intStatus'] == 1 ? ' selected':'';?>>Active</option>
                                                    <option value="2"<?php echo isset($arrReturn['data']['intStatus']) && $arrReturn['data']['intStatus'] == 2 ? ' selected':'';?>>Inactive</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Cập nhật</button>
                        <button type="button" class="btn btn-default">Hủy</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</section><!-- /.content -->
<?php
if ($arrReturn['is_post'] == 1) {
    ?>
    <script type="text/javascript">
        $(document).ready(function () {
            bootbox.dialog({
                message: '<?php echo $arrReturn['msg'];?>',
                title: 'Thông báo',
                title_className: 'bg-primary',
                buttons: {
                    close: {
                        label: "Close",
                        className: "btn-default",
                        callback: function () {
                        }
                    }
                }
            });
            <?php
            if($arrReturn['error'] == 0)
            {
            ?>
            setTimeout(function () {
                location.href = SITE_URL + '/backend/pages/index';
            }, 2000);
            <?php
            }
            ?>
        });
    </script>
<?php
}
?>