version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.21-alpine
    restart: always
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./nhathepsaigon.vn:/var/www/nhathepsaigon.vn
      - ./nhago3h.vn:/var/www/nhago3h.vn
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - phpmyadmindata:/var/www/phpmyadmin
    depends_on:
      - nhathepsaigon
      - nhago3h
      - phpmyadmin

  # http://nhathepsaigon.vn Service
  nhathepsaigon:
    build: ./.docker/php
    working_dir: /var/www/nhathepsaigon.vn
    volumes:
      - ./nhathepsaigon.vn:/var/www/nhathepsaigon.vn
    depends_on:
      mysql:
        condition: service_healthy

  # http://nhago3h.vn Service
  nhago3h:
    build: ./.docker/php
    working_dir: /var/www/nhago3h.vn
    volumes:
      - ./nhago3h.vn:/var/www/nhago3h.vn
    depends_on:
      mysql:
        condition: service_healthy

  # PhpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5-fpm-alpine
    environment:
      PMA_HOST: ${DB_HOST}
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./.docker/db:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

# Redis Service
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - redisdata:/var/lib/redis

# Volumes
volumes:
  phpmyadmindata:
  mysqldata:
  redisdata:
   