<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Thông báo</h3>
                </div>
                <div class="box-body">
                    <div class="alert alert-danger alert-dismissable" role="alert">Bạn không có quyền truy cập chức năng này!</div>
                </div>
            </div>
        </div>
    </div>
</section><!-- /.content -->