<!--Wrap Success-->
<div class="col-md-12 main-content">
<div class="wrap-success">
    <p><img class="lazy" data-original="<?php echo STATIC_URL; ?>/fe/images/success_img.png" src="<?php echo STATIC_URL; ?>/fe/images/success_img.png" alt="Thành công" /></p>
    <p class="tc_txt">Bạn đã kích hoạt tài khoản thành công.</p>
    <p>Bạn có thể dùng tài khoản này để gửi bài đăng lên <?php echo $this->arrConfig['web_name'];?>.</p>
    <p>Bấm vào <a href="<?php echo SITE_URL; ?>/gui-bai"><strong style="color: #d71450;">đây</strong></a> để gửi bài đăng lên <?php echo $this->arrConfig['web_name'];?>.</p>
</div>
<!--End Wrap Success-->
</div>