<?php
$arrUserDetail = $this->arrUserDetail;
if(isset($arrUserDetail['birthday'])) {
    //format date
    $arrUserDetail['birthday'] = isset($arrUserDetail['birthday']) ? date('d/m/Y',$arrUserDetail['birthday']) : '';
}
?>
<form class="form" id="edit" method="post" action="" role="form">
    <div class="col-md-8 main-content">
        <!-- row ads -->
        <div class="row content-ads">
            <div class="col-md-12">
                <img class="lazy" data-original="<?php echo STATIC_URL; ?>/fe/images/qc-728x90.png" src="<?php echo STATIC_URL; ?>/fe/images/qc-728x90.png" alt="ads">
            </div>
        </div>
        <div class="form-group frm-validate">
            <label for="strCateName">Email</label>
            <input readonly type="text" value="<?php echo isset($arrUserDetail['email'])?$arrUserDetail['email']:'';?>" class="form-control" id="strEmail" placeholder="Email">
            <!-- /.input group -->
        </div>
        <div class="form-group frm-validate">
            <label for="strFullname">Họ tên</label>
            <input type="text" name="strFullname" value="<?php echo isset($arrUserDetail['fullname'])?$arrUserDetail['fullname']:'';?>" class="form-control" id="strFullname" placeholder="Họ tên">
        </div>
        <!-- Date dd/mm/yyyy -->
        <div class="form-group frm-validate">
            <label for="strBirthday">Ngày sinh</label>
            <input type="text" value="<?php echo isset($arrUserDetail['birthday']) ? $arrUserDetail['birthday'] : '';?>" name="strBirthday" class="form-control" id="strBirthday" placeholder="Ngày sinh">
            <!-- /.input group -->
        </div>
        <div class="form-group frm-validate">
            <label for="strAddress">Địa chỉ</label>
            <input type="text" name="strAddress" value="<?php echo isset($arrUserDetail['address'])?$arrUserDetail['address']:'';?>" class="form-control" id="strAddress" placeholder="Địa chỉ">
        </div>
        <div class="form-group frm-validate">
            <label for="strPhone">Số điện thoại</label>
            <input type="text" name="strPhone" value="<?php echo isset($arrUserDetail['phone'])?$arrUserDetail['phone']:'';?>" class="form-control" id="strPhone" placeholder="Điện thoại">
        </div>
        <div class="form-group frm-validate">
            <label for="strPhone">Giới tính</label>
            <select class="form-control" name="intGender">
                <option value="1"<?php echo (isset($arrUserDetail['gender']) && $arrUserDetail['gender'] == 1)?' selected':'';?>>Nam</option>
                <option value="0"<?php echo (isset($arrUserDetail['gender']) && $arrUserDetail['gender'] == 0)?' selected':'';?>>Nữ</option>
                <option value="2"<?php echo (isset($arrUserDetail['gender']) && $arrUserDetail['gender'] == 2)?' selected':'';?>>Không xác định</option>
            </select>
        </div>
        <input style="float: right;" type="submit" value="Hoàn thành" class="btn btn-primary" id="btn_send_article">
    </div>
    <div class="col-md-4 right-sidebar">
        <a title="Liên hệ quảng cáo" href="<?php echo SITE_URL;?>/lien-he-quang-cao"><img class="lazy" data-original="<?php echo STATIC_URL; ?>/fe/images/qc-317x264.png" src="<?php echo STATIC_URL; ?>/fe/images/qc-317x264.png" alt="ads sidebar"></a>
    </div>
</form>