<!--Wrap Success-->
<div class="col-md-12 main-content">
    <div class="wrap-success">
        <p><img class="lazy" data-original="<?php echo STATIC_URL; ?>/fe/images/success_img.png" src="<?php echo STATIC_URL; ?>/fe/images/success_img.png" alt="Thành công" /></p>
        <p class="tc_txt">Lấy lại mật khẩu không thành công.</p>
        <p>Đã có lỗi xảy ra trong quá trình lấy lại mật khẩu hoặc link lấy lại mật khẩu của bạn đã quá hạn.</p>
        <p>Bấm vào <a href="<?php echo SITE_URL; ?>/gui-bai"><strong style="color: #d71450;">đây</strong></a> để trở về trang chủ.</p>
    </div>
    <!--End Wrap Success-->
</div>