<form class="form" id="reset-pass" method="post" action="" role="form">
    <div class="col-md-8 main-content">
        <!-- row ads -->
        <div class="row content-ads">
            <div class="col-md-12">
                <img class="lazy" data-original="<?php echo STATIC_URL; ?>/fe/images/qc-728x90.png" src="<?php echo STATIC_URL; ?>/fe/images/qc-728x90.png" alt="ads">
            </div>
        </div>
        <div class="width_common">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group frm-validate has-feedback">
                        <input name="strPass" type="password" class="form-control" placeholder="Mật khẩu mới">
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    </div>
                    <div class="form-group frm-validate has-feedback">
                        <input name="strConfirmPass" type="password" class="form-control" placeholder="Xác nhận mật khẩu mới">
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    </div>
                </div>
            </div>
        </div>
        <input style="float: right;" type="submit" value="Hoàn thành" class="btn btn-primary" id="btn_send_article">
    </div>
    <div class="col-md-4 right-sidebar">
        <a title="Liên hệ quảng cáo" href="<?php echo SITE_URL;?>/lien-he-quang-cao"><img class="lazy" data-original="<?php echo STATIC_URL; ?>/fe/images/qc-317x264.png" src="<?php echo STATIC_URL; ?>/fe/images/qc-317x264.png" alt="ads sidebar"></a>
    </div>
</form>