<!DOCTYPE html>
<html lang="vi" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'>
    <link rel="shortcut icon" type="image/png" href="<?php echo STATIC_URL; ?>/be/images/favicon.png" />
    <!-- Bootstrap 3.3.5 -->
    <link href="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!--<link href="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/css/bootstrap-theme.min.css" rel="stylesheet" type="text/css" />-->
    <!-- iCheck for checkboxes and radio inputs -->
    <link href="<?php echo STATIC_URL; ?>/library/plugins/iCheck/all.css" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="<?php echo STATIC_URL; ?>/library/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="<?php echo STATIC_URL; ?>/library/ionicons-2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="<?php echo STATIC_URL;?>/be/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo STATIC_URL;?>/library/bootstrap-3.3.6/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo STATIC_URL;?>/library/bootstrap-3.3.6/css/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css" />
    <!-- Admin Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link href="<?php echo STATIC_URL;?>/be/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo STATIC_URL;?>/be/css/main.css" rel="stylesheet" type="text/css" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="<?php echo STATIC_URL; ?>/library/js/html5shiv.js" type="text/javascript"></script>
    <script src="<?php echo STATIC_URL; ?>/library/js/respond.min.js" type="text/javascript"></script>
    <![endif]-->
    <!-- jquery 2.2.4 -->
    <script src="<?php echo STATIC_URL; ?>/library/js/jquery-2.2.4.min.js" type="text/javascript"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="<?php echo STATIC_URL; ?>/library/js/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- SlimScroll -->
    <script src="<?php echo STATIC_URL; ?>/library/js/jquery.slimscroll.min.js" type="text/javascript"></script>
    <!-- FastClick -->
    <script src='<?php echo STATIC_URL; ?>/library/js/fastclick.min.js' type="text/javascript"></script>
    <!-- Js validate -->
    <script src="<?php echo STATIC_URL; ?>/library/js/jquery.validate.min.js" type="text/javascript"></script>
    <!-- daterangepicker -->
    <script src="<?php echo STATIC_URL; ?>/library/js/moment.min.js"></script>
    <script src="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/js/daterangepicker.js"></script>
    <!-- datepicker -->
    <!--<script src="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/js/bootstrap-datepicker.min.js"></script>-->
    <script src="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/js/datepicker.js"></script>
    <!-- datepicker -->
    <script src="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/js/bootstrap-datetimepicker.min.js"></script>
    <!-- Js datetimepicker -->
    <script src="<?php echo STATIC_URL; ?>/library/js/bootbox.min.js" type="text/javascript"></script>
    <!-- Js dynatree -->
    <!--<script src="<?php echo STATIC_URL; ?>/library/js/jquery.cookie.js" type="text/javascript"></script>-->
    <!-- iCheck 1.0.1 -->
    <script src="<?php echo STATIC_URL; ?>/library/plugins/iCheck/icheck.min.js"></script>
    <!--<script src="<?php echo STATIC_URL; ?>/library/js/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>-->
    <!--<script src="<?php echo STATIC_URL; ?>/library/js/jquery.dynatree.min.js" type="text/javascript"></script>-->
    <!-- AdminLTE App -->
    <script src="<?php echo STATIC_URL; ?>/library/js/app.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        var SITE_URL = '<?php echo SITE_URL;?>';
        var STATIC_URL = '<?php echo STATIC_URL;?>';
    </script>
    <?php
    echo $this->headTitle();
    echo $this->headLink();
    ?>
</head>
<!-- ADD THE CLASS fixed TO GET A FIXED HEADER AND SIDEBAR LAYOUT -->
<body class="skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

<header class="main-header">
    <a title="<?php echo $this->arrConfig['web_name']; ?>" href="<?php SITE_URL;?>/backend" class="logo be-logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>NE</b></span>
        <!-- logo for regular state and mobile devices -->
        <img style="padding-bottom: 5px;" alt="<?php echo $this->arrConfig['web_name']; ?>" src="<?php echo STATIC_URL; ?>/fe/images/logo_nhadepsaithanh.png">
    </a>
    <!--<a href="<?php SITE_URL;?>/backend" class="logo"><b>Contents Editors</b></a>-->
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="javascript:;" class="sidebar-toggle" data-toggle="offcanvas" role="button"></a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                        <!--<img src="<?php echo STATIC_URL;?>/be/images/user3-128x128.jpg" class="user-image" alt="User Image"/>-->
                        <span class="hidden-xs"><?php echo $this->user['fullname'];?></span>
                    </a>
                    <!--<ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="<?php echo STATIC_URL;?>/be/images/user3-128x128.jpg" class="img-circle" alt="User Image" />
                            <p>
                                Trần Xuân Phong - Web Developer
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="<?php SITE_URL;?>/backend/users/logout" class="btn btn-default btn-flat">Thoát</a>
                            </div>
                        </li>
                    </ul>-->
                </li>
            </ul>
        </div>
    </nav>
</header>

<!-- =============================================== -->

<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- search form -->
        <!--<form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Tìm kiếm..."/>
              <span class="input-group-btn">
                <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
        </form>-->
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu">
            <li class="header" style="padding:0px; height:1px;"></li>
            <li class="treeview<?php echo $this->controllerName=='index'?' active':'';?>">
                <a href="<?php echo SITE_URL;?>/backend">
                    <i class="fa fa-th"></i><span>Dashboard</span>
                </a>
            </li>
            <li class="treeview<?php echo $this->controllerName=='crawler'?' active':'';?>">
                <a href="javascript:;">
                    <i class="fa fa-edit"></i><span>Quản lý crawler data</span><i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <!--<li<?php echo $this->controllerName=='crawler' && $this->actionName=='index' ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/crawler/index"><i class="fa fa-angle-right"></i>List data crawler</a></li>-->
                    <li<?php echo $this->controllerName=='crawler' && $this->actionName=='link-detail' ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/crawler/link-detail"><i class="fa fa-angle-right"></i>Crawler theo link chi tiết</a></li>
                    <!--<li<?php echo $this->controllerName=='crawler' && $this->actionName=='import' ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/crawler/import"><i class="fa fa-angle-right"></i>Import data crawler RSS</a></li>-->
                </ul>
            </li>
            <li class="treeview<?php echo $this->controllerName=='articles' || $this->controllerName=='categories' || $this->controllerName=='tags' || $this->controllerName=='topics'?' active':'';?>">
                <a href="javascript:;">
                    <i class="fa fa-edit"></i><span>Quản lý tin tức</span><i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li<?php echo $this->controllerName=='articles' && $this->actionName=='add' && $this->type == 1 ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/articles/add/type/1"><i class="fa fa-angle-right"></i>Tạo bài viết mới</a></li>
                    <!--<li<?php echo $this->controllerName=='articles' && $this->actionName=='add' && $this->type == 2 ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/articles/add/type/2"><i class="fa fa-angle-right"></i>Tạo mới video</a></li>
                    <li<?php echo $this->controllerName=='articles' && $this->actionName=='index' && $this->status == STATUS_CHO_DUYET ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/articles/index/status/2"><i class="fa fa-angle-right"></i>Chờ duyệt</a></li>-->
                    <li<?php echo $this->controllerName=='articles' && $this->actionName=='index' && $this->status == STATUS_DA_DUYET ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/articles/index/status/1"><i class="fa fa-angle-right"></i>Danh sách bài viết</a></li>
                    <!--<li<?php echo $this->controllerName=='articles' && $this->actionName=='index' && $this->status == STATUS_LUU_NHAP ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/articles/index/status/3"><i class="fa fa-angle-right"></i>Lưu nháp</a></li>-->
                    <li><a href="<?php echo SITE_URL;?>/backend/categories/index/type/1"><i class="fa fa-angle-right"></i>Danh mục</a></li>
                    <li><a href="<?php echo SITE_URL;?>/backend/tags/index"><i class="fa fa-angle-right"></i>Tags</a></li>
                    <!--<li><a href="<?php echo SITE_URL;?>/backend/topics/index"><i class="fa fa-angle-right"></i>Topics</a></li>-->
                </ul>
            </li>
            <li class="treeview<?php echo $this->controllerName=='pages'?' active':'';?>">
                <a href="javascript:;">
                    <i class="fa fa-edit"></i><span>Quản lý trang tĩnh</span><i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li<?php echo $this->controllerName=='pages' && $this->actionName=='add' ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/pages/add"><i class="fa fa-angle-right"></i>Tạo trang tĩnh</a></li>
                    <li<?php echo $this->controllerName=='pages' && $this->actionName=='index' ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/pages/index"><i class="fa fa-angle-right"></i>Danh sách trang tĩnh</a></li>
                </ul>
            </li>
            <!--<li class="treeview<?php echo $this->controllerName=='comments'?' active':'';?>">
                <a href="javascript:;">
                    <i class="fa fa-comments"></i> <span>Quản lý bình luận</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li<?php echo $this->controllerName=='comments' && ($this->actionName=='index') && $this->status == STATUS_CHO_DUYET ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/comments/index/status/2"><i class="fa fa-angle-right"></i>Chờ duyệt</a></li>
                    <li<?php echo $this->controllerName=='comments' && ($this->actionName=='index') && $this->status == STATUS_DA_DUYET ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/comments/index/status/1"><i class="fa fa-angle-right"></i>Đã duyệt</a></li>
                    <li<?php echo $this->controllerName=='comments' && ($this->actionName=='index') && $this->status == STATUS_LUU_NHAP ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/comments/index/status/3"><i class="fa fa-angle-right"></i>Từ chối duyệt</a></li>
                </ul>
            </li>
            <li class="treeview<?php echo $this->controllerName=='positions' || $this->controllerName=='banners'?' active':'';?>">
                <a href="javascript:;">
                    <i class="fa fa-picture-o"></i> <span>Quản quảng cáo</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li<?php echo $this->controllerName=='positions' && ($this->actionName=='index') ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/positions/index"><i class="fa fa-angle-right"></i>Vị trí quảng cáo</a></li>
                    <li<?php echo $this->controllerName=='banners' && ($this->actionName=='index') ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/banners/index"><i class="fa fa-angle-right"></i>Quảng cáo</a></li>
                    <li<?php echo $this->controllerName=='banners' && ($this->actionName=='text') ? ' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/banners/text"><i class="fa fa-angle-right"></i>Text banner</a></li>
                </ul>
            </li>-->
            <li class="treeview<?php echo $this->controllerName=='users' || $this->controllerName=='menus' || $this->controllerName=='groups' || $this->controllerName=='config'?' active':'';?>">
                <a href="javascript:;">
                    <i class="fa fa-cog"></i> <span>Quản lý hệ thống</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li<?php echo $this->controllerName=='users' && ($this->actionName=='index')?' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/users"><i class="fa fa-angle-right"></i>Users</a></li>
                    <!--<li<?php echo $this->controllerName=='groups' && ($this->actionName=='index')?' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/groups"><i class="fa fa-angle-right"></i>Nhóm quyền</a></li>
                    <li<?php echo $this->controllerName=='menus' && ($this->actionName=='index')?' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/menus"><i class="fa fa-angle-right"></i>Menus admin</a></li>-->
                    <li<?php echo $this->controllerName=='config' && ($this->actionName=='index')?' class="active"':'';?>><a href="<?php echo SITE_URL;?>/backend/config"><i class="fa fa-angle-right"></i>Cấu hình chung</a></li>
                </ul>
            </li>
            <li>
                <a href="<?php SITE_URL;?>/backend/users/logout">
                    <i class="fa fa-sign-out"></i> <span>Thoát</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

<!-- =============================================== -->

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <?php echo $this->layout()->content; ?>
</div><!-- /.content-wrapper -->
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0
    </div>
    <strong>Copyright &copy; 2016 <a href="<?php echo SITE_URL;?>"><?php echo $this->arrConfig['web_name'];?></a>. </strong> All rights reserved.
</footer>
</div><!-- ./wrapper -->
<?php echo $this->headScript(); ?>
</body>
</html>
