<html lang="vi" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'>
    <!--<link rel="shortcut icon" href="<?php echo SITE_URL; ?>/favicon.ico" type="image/x-icon" />-->
    <link rel="shortcut icon" type="image/png" href="<?php echo SITE_URL; ?>/favicon.png" />
    <!-- Bootstrap 3.3.5 -->
    <link href="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- Login -->
    <link href="<?php echo STATIC_URL;?>/be/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo STATIC_URL;?>/be/css/login.css" rel="stylesheet" type="text/css" />
    <!--<link href="<?php echo STATIC_URL;?>/be/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />-->
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="<?php echo STATIC_URL; ?>/library/js/html5shiv.min.js" type="text/javascript"></script>
    <script src="<?php echo STATIC_URL; ?>/library/js/respond.min.js" type="text/javascript"></script>
    <![endif]-->
    <!-- jQuery 2.1.4 -->
    <script src="<?php echo STATIC_URL; ?>/library/js/jQuery-2.1.4.min.js" type="text/javascript"></script>
    <!-- Bootstrap 3.3.4 JS -->
    <script src="<?php echo STATIC_URL; ?>/library/bootstrap-3.3.6/js/bootstrap.min.js" type="text/javascript"></script>
    <!-- Js validate -->
    <script src="<?php echo STATIC_URL; ?>/library/js/jquery.validate.min.js" type="text/javascript"></script>
    <?php
    echo $this->headTitle();
    echo $this->headLink();
    ?>
</head>
<body class="login-page">
    <div class="login-box">
        <?php echo $this->layout()->content; ?>
    </div>
<?php echo $this->headScript(); ?>
</body>
</html>