<!-- section -->
<div class="section">
    <!-- container -->
    <div class="news container">
        <!-- row -->
        <div class="row">
            <!-- section title -->
            <div class="col-md-12">
                <div class="section-title">
                    <h2 class="title"><?php echo $this->arrPageDetail['name'];?></h2>
                </div>
            </div>
            <!-- section title -->

            <!-- Product Single -->
            <div class="col-md-12 col-sm-12 col-xs-12">
                <?php echo $this->arrPageDetail['content'];?>
            </div>
            <!-- /Product Single -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /section -->