<?php
$arrData = $this->arrData;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <ol class="breadcrumb">
            <li><a href="<?php echo SITE_URL;?>/backend"><i class="fa fa-th"></i> Dashboard</a></li>
            <li><a href="<?php echo SITE_URL;?>/backend/topics/index/type/<?php echo $this->intTopicType;?>" title="Chủ đề">Chủ đề</a></li>
        </ol>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!--<div class="callout callout-info">
        <h4>Thông báo</h4>
        <p>Cập nhật thành công</p>
    </div>-->
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">&nbsp</h3>

                    <div class="box-tools pull-right">
                        <a href="javascript:;" class="btn btn-add act-add btn-block btn-primary btn-sm" data-topic-id="0" data-toggle="modal" data-target="#modal-add">Tạo mới</a>
                    </div>
                </div>
                <?php
                if(!empty($arrData['data'])){
                ?>
                    <!-- /.box-header -->
                    <div class="box-header clearfix">
                        <?php echo $this->Pagination($arrData['total'], $arrData['intPage'], $arrData['intLimit'], 1); ?>
                    </div>
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-bordered table-striped">
                            <tr>
                                <th class="txt-id text-center">ID</th>
                                <th>Name</th>
                                <th class="txt-action text-center text-nowrap">Action</th>
                            </tr>
                            <?php
                            if(!empty($arrData['data'])) {
                                foreach($arrData['data'] as $row) {
                                    ?>
                                    <tr>
                                        <td class="text-center"><?php echo $row['topic_id'];?></td>
                                        <td><a class="tooltips act-add" data-topic-id="<?php echo $row['topic_id'];?>" data-toggle="modal" data-target="#modal-add" href="javascript:;" data-original-title="Edit"><?php echo $row['topic_name'];?></a></td>
                                        <td class="text-center">
                                            <a class="tooltips act-add" data-topic-id="<?php echo $row['topic_id'];?>" data-toggle="modal" data-target="#modal-add" href="javascript:;" data-original-title="Edit">
                                                <i class="fa fa-edit"></i>
                                            </a>&nbsp;
                                            <a class="tooltips act-update-status" data-id="<?php echo $row['topic_id'];?>" data-name="<?php echo $row['topic_name'];?>" data-status="<?php echo $row['status'];?>" href="javascript:;" data-toggle="tooltip" data-original-title="<?php echo $row['status']==1?'Inactive':'Active';?>">
                                                <i class="fa <?php echo $row['status']==1?'fa-lock':'fa-unlock';?>"></i>
                                            </a>
                                            &nbsp;
                                            <a class="tooltips act-del" data-id="<?php echo $row['topic_id'];?>" data-name="<?php echo $row['topic_name'];?>" href="javascript:;" data-toggle="tooltip" data-original-title="Delete">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                        </td>
                                    </tr>
                                <?php
                                }
                            }
                            ?>
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <?php echo $this->Pagination($arrData['total'], $arrData['intPage'], $arrData['intLimit'], 1); ?>
                    </div>
                <?php
                }else{
                    ?>
                    <div class="box-body">
                        <div class="alert alert-warning p-b-10" role="alert">Không tìm thấy dữ liêu!</div>
                    </div>
                <?php
                }
                ?>
            </div>
            <!-- /.box -->
        </div>
    </div>
    <div class="modal fade" id="modal-add" role="dialog" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
</section><!-- /.content -->