<?php
$arrData = $this->arrData;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        <ol class="breadcrumb">
            <li><a href="<?php echo SITE_URL;?>/backend"><i class="fa fa-th"></i> Dashboard</a></li>
            <li><a href="<?php echo SITE_URL;?>/backend/users" title="Users">Users</a></li>
        </ol>
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <!--<div class="callout callout-info">
        <h4>Thông báo</h4>
        <p>Cập nhật thành công</p>
    </div>-->
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <h3 class="box-title">Users</h3>

                    <div class="box-tools pull-right">
                        <a href="javascript:;" class="btn btn-add act-add btn-block btn-primary btn-sm" data-id="0" data-toggle="modal" data-target="#modal-add">Tạo mới</a>
                    </div>
                </div>
                <?php
                if(!empty($arrData['data'])){
                ?>
                    <!-- /.box-header -->
                    <div class="box-header clearfix">
                        <?php echo $this->Pagination($arrData['total'], $arrData['intPage'], $arrData['intLimit'], 1); ?>
                    </div>
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-bordered table-striped">
                            <tr>
                                <th class="text-center">ID</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th class="text-center text-nowrap">Status</th>
                                <th class="text-center text-nowrap">Action</th>
                            </tr>
                            <?php
                            if(!empty($arrData['data'])) {
                                foreach($arrData['data'] as $row) {
                                    switch($row['status'])
                                    {
                                        case 1:
                                            $status = 'Active';
                                            break;
                                        case 2:
                                            $status = 'Inactive';
                                            break;
                                    }
                                    ?>
                                    <tr>
                                        <td class="text-center"><?php echo $row['user_id'];?></td>
                                        <td><a class="act-add" data-id="<?php echo $row['user_id'];?>" data-target="#modal-add" href="javascript:;" data-toggle="tooltip" title="Edit"><?php echo $row['fullname'];?></a></td>
                                        <td><?php echo $row['email'];?></td>
                                        <td class="text-center"><?php echo $status;?></td>
                                        <td class="text-center">
                                            <?php
                                            if($row['user_id'] != 1) {
                                                ?>
                                                <a class="act-add" data-id="<?php echo $row['user_id']; ?>"
                                                   data-target="#modal-add" href="javascript:;" data-toggle="tooltip"
                                                   title="Edit">
                                                    <i class="fa fa-edit"></i>
                                                </a>&nbsp;
                                                <a class="act-reset" data-id="<?php echo $row['user_id']; ?>"
                                                   data-email="<?php echo $row['email']; ?>"
                                                   data-name="<?php echo $row['fullname']; ?>" data-target="#modal-reset"
                                                   href="javascript:;" data-toggle="tooltip" title="Reset password">
                                                    <i class="fa fa-key"></i>
                                                </a>&nbsp;
                                                <a class="act-update-status" data-id="<?php echo $row['user_id']; ?>"
                                                   data-name="<?php echo $row['fullname']; ?>"
                                                   data-status="<?php echo $row['status']; ?>" href="javascript:;"
                                                   data-toggle="tooltip"
                                                   title="<?php echo $row['status'] == 1 ? 'Inactive' : 'Active'; ?>">
                                                    <i class="fa <?php echo $row['status'] == 1 ? 'fa-lock' : 'fa-unlock'; ?>"></i>
                                                </a>
                                                &nbsp;
                                                <a class="act-del" data-id="<?php echo $row['user_id']; ?>"
                                                   data-name="<?php echo $row['fullname']; ?>" href="javascript:;"
                                                   data-toggle="tooltip" title="Delete">
                                                    <i class="fa fa-trash-o"></i>
                                                </a>
                                            <?php
                                            }
                                            ?>
                                        </td>
                                    </tr>
                                <?php
                                }
                            }
                            ?>
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <?php echo $this->Pagination($arrData['total'], $arrData['intPage'], $arrData['intLimit'], 1); ?>
                    </div>
                <?php
                }else{
                    ?>
                    <div class="box-body">
                        <div class="alert alert-warning p-b-10" role="alert">Không tìm thấy dữ liêu!</div>
                    </div>
                <?php
                }
                ?>
            </div>
            <!-- /.box -->
        </div>
    </div>
    <div class="modal fade" id="modal-add" role="dialog" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
    <div class="modal fade" id="modal-reset" role="dialog" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content">
                <form id="frm-user-reset" action="" method="POST" role="form">
                    <input type="hidden" name="intUserId" value="0">
                    <div class="modal-header">
                        <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title">Reset password</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group frm-validate">
                            <label for="strEmail">Email</label>
                            <input readonly type="text" name="strEmail" value="" class="form-control" id="strEmail" placeholder="Email">
                        </div>
                        <div class="form-group frm-validate">
                            <label for="strPassWord">Mật khẩu mới</label>
                            <input type="password" name="strPassWord" value="" class="form-control" id="strPassWord" placeholder="Mật khẩu mới">
                        </div>
                        <div class="form-group frm-validate">
                            <label for="strConfirmPassWord">Xác nhận mật khẩu mới</label>
                            <input type="password" name="strConfirmPassWord" value="" class="form-control" id="strConfirmPassWord" placeholder="Xác nhận mật khẩu mới">
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary btn-save">Cập nhật</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                    </div>
                </form>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div>
</section><!-- /.content -->