<?php
$cateDetail = $this->cateDetail;
$arrTopNews = $this->arrTopNews;
$arrData = $this->arrData;
?>
<!-- section -->
<div class="section">
    <!-- container -->
    <div class="news container">
        <!-- row -->
        <div class="row">
            <!-- section title -->
            <div class="col-md-12">
                <div class="section-title">
                    <h2 class="title"><?php echo $cateDetail['cate_name']; ?></h2>
                </div>
            </div>
            <!-- section title -->
            <?php
            foreach ($arrData['data'] as $row) {
                ?>
                <!-- Product Single -->
                <div class="col-md-4 col-sm-6 col-xs-6">
                    <div class="product product-single">
                        <a href="<?php echo SITE_URL . $row['share_url']; ?>" title="<?php echo $this->escape($row['title']); ?>" class="product-thumb">
                            <img class="lazy" data-original="<?php echo $this->ImageurlArticle($row, 'size1'); ?>" src="<?php echo $this->ImageurlArticle($row, 'size1'); ?>" alt="<?php echo $this->escape($row['title']); ?>">
                        </a>
                        <div class="product-body">
                            <h1 class="news-title"><a href="<?php echo SITE_URL . $row['share_url']; ?>" title="<?php echo $this->escape($row['title']); ?>"><?php echo $row['title']; ?></a></h1>
                            <h2 class="news-desc"><?php echo $this->CropWord($row['lead'],40); ?></h2>
                        </div>
                    </div>
                </div>
                <!-- /Product Single -->
                <?php
            }
            ?>
        </div>
        <!-- /row -->
        <!-- row -->
        <div class="row">
            <div class="pagination_news right"><?php echo $this->Paginationfe($this->arrParamPaging); ?></div>
        </div>
    </div>
    <!-- /container -->
</div>
<!-- /section -->